### ISSUE TITLE
Wasted SRAM

### ISSUE THREAD

**Issue by jimmys01** [computourist/ESP8266-MQTT-client#6]
Statments as 
Serial.println("connected");
can be 
Serial.println(F("connected"));
and do some major savings in SRAM for the arduino..

I presume you know that? 

Anyway THANKS for your code is AWSOME and it works!

**Comment by computourist** [comment]
Hi Jimmys01,

Thanks for the hint. In my final code (ESP_SONOFF_12-code) the line printing is only done for debugging. Since I have not have had memory limitations I did not look into this.
