### ISSUE TITLE
function of devices 5,6 and 7

### ISSUE THREAD

**Issue by consolacion** [computourist/ESP8266-MQTT-client#8]
I feel a bit stupid asking, but what do the devices 5,6 and 7 actually do?
"05 	read/set acknowledge message after a 'set' request" I am not fully what it means. I presume that it determines whether each read of an individual device is followed by a  confirmation, but I am just guessing
"6 toggle: read/set select toggle / timer function" I really have no idea what that actually does. Suppose it says "ON"  what does that mean/do? I guess I just dont see what it Toggles between
"7 timer: read/set timer interval in seconds" That one ofcourse I understand, but what exactly does it time?

**Comment by computourist** [comment]
device 5: if set, every command sent to the node gets acknowledged by a separate MQTT message from the node. So, when you send a message to switch the output to ON, the node will immediately respond with a message stating the output is ON.
device 6: you can instruct the behaviour of the button on the node to act as:
- toggle: toggles local output
- timer: starts a timer for output ON. After a set the local output will turn off
device 7: set/read the timer interval.

Hope this helps...

**Comment by consolacion** [comment]
Ah OK, thanks a bundle
and again, great article in Elektuur.

For Sonoff the Tasmota software is very popular, but I find yours definitely handier. Really happy with it
i will add an OTA though. ;-) (Not just using it on SonOff)

**Comment by computourist** [comment]
These devices only act as a local function: they are controlled by the local button on the node.  If you want to toggle over MQTT you would have to send separate ON OFF messages.

**Comment by consolacion** [comment]
yes, I understand :-) I had sort of forgotten the local button
