### ISSUE TITLE
IP nr disappearing

### ISSUE THREAD

**Issue by consolacion** [computourist/ESP8266-MQTT-client#9]
Have been using the SONOFF_12  package for most of my ESP nodes, sonoff or not and It is really great software.
Just a little thing: I noticed that after a while... without changing anything, device 10, the IP number becomes empty. Have not figured out why yet. Not a huge problem, just a bit of a nuisance

**Comment by computourist** [comment]
Strange...
I'll query my nodes. They have been up & running for months, so we'll see.
Give me a couple of days..

**Comment by consolacion** [comment]
No hurry whatsoever

**Comment by computourist** [comment]
Just checked my esp-node: All OK: 

![afbeelding](https://user-images.githubusercontent.com/10297518/33231750-b6eae766-d1fa-11e7-9a1a-133c7b3533db.png)

**Comment by consolacion** [comment]
Thanks, I did some checks too: I would expect the IP number to appear again after a reset of the ESP...it didnt. What did help though was a reset of my router. So,I guess the problem is not with yr code, but somewhere else.
However, i dont recall seeing it in other codes... as far as i remember, will keep an eye on that. Anyway for now I think the problem somehow is with my router
